-- AlterTable
ALTER TABLE "Employee" ALTER COLUMN "birthDate" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Holiday" ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "endDate" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Leave" ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "endDate" SET DATA TYPE TEXT;
